### ISSUE TITLE
Error in EN 18031-1 template: Incorrect reference to non-existent node in decision tree

### ISSUE THREAD

**Issue by mmue** [zealience/IoT-Cybersecurity-Compliance#1]
The template for EN 18031-1 contains an incorrect reference to "DT.AUM-3.DN-2" in the sheet named "AUM-3.AUM." This node does not exist in the standard, as the decision tree for this section includes only one node.

**Comment by zealience** [comment]
Thanks a lot for reporting the issue! We uploaded the new v1.1 reflecting the changes.

Do not hesitate if you have suggestions on how to improve the template.
